import type { Localized } from "./catalog";

/**
 * Guides.
 *
 * Written to answer the questions buyers type before they contact anyone —
 * which is also what they rank for. Each is a genuine explanation, not a
 * keyword page, and ends by pointing the reader at the equipment it discusses.
 *
 * Slugs are translated, not transliterated: an Arabic reader searches in
 * Arabic. Bodies are Markdown, rendered by lib/markdown.ts.
 */

export interface Guide {
  slug: Localized;
  title: Localized;
  excerpt: Localized;
  body: Localized;
  /** Equipment categories the guide is about, for links at the end. */
  categories: string[];
  /** ISO date the content was last reviewed. */
  updated: string;
}

export const GUIDES: Guide[] = [
  {
    slug: { en: "what-size-crane-do-i-need", ar: "ما-حجم-الرافعة-التي-احتاجها" },
    title: { en: "What size crane do I need?", ar: "ما حجم الرافعة التي أحتاجها؟" },
    excerpt: { en: "Capacity alone does not tell you whether a crane can make your lift. Radius does.", ar: "الحمولة وحدها لا تحدد ما إذا كانت الرافعة قادرة على تنفيذ عملية الرفع. نصف القطر هو ما يحدد ذلك." },
    body: {
      en: "The most common mistake in crane selection is reading the headline capacity as if it were the answer.\n\nA \"100 tonne crane\" can lift 100 tonnes only in the most favourable configuration: shortest boom, minimum radius, full counterweight, on level prepared ground. At 30 metres radius the same machine may be rated for a small fraction of that.\n\n## The four numbers that decide it\n\n**Load weight.** The actual mass of what is being lifted, plus rigging: slings, shackles, spreader bars and any lifting beam. Rigging routinely adds several hundred kilograms and is frequently forgotten.\n\n**Radius.** The horizontal distance from the crane's centre of rotation to the centre of the load — at the point of set-down, not at pick-up. This is usually the binding constraint, and it is the number most often underestimated.\n\n**Lift height.** How high the hook must travel, including the height of the load itself, the rigging, and clearance over any obstruction.\n\n**Ground conditions.** Outrigger loads are concentrated and large. A crane that fits the load chart on paper and sinks an outrigger through a service duct has not made the lift.\n\n## How to use a load chart\n\nEvery crane has a load chart giving safe working loads for each boom length and radius combination. Read down to your radius, across to your boom configuration, and compare the figure to your total load including rigging. If you are within roughly 80% of the chart figure, look at the next class up — margin absorbs the wind allowance, the weight you were not told about, and the radius that turned out to be longer than the drawing.\n\n## The limit of any online tool\n\nSend us the load weight, radius and lift height and we can suggest crane classes worth considering. That is a starting point, not a lift plan: final equipment suitability, the ground bearing assessment and the lift plan itself must be confirmed by a qualified lifting engineer who has seen the site.",
      ar: "أكثر الأخطاء شيوعاً في اختيار الرافعة هو قراءة الحمولة المعلنة وكأنها الإجابة النهائية.\n\n\"الرافعة بحمولة 100 طن\" لا ترفع 100 طن إلا في أفضل التكوينات: أقصر ذراع، وأدنى نصف قطر، وكامل الأثقال الموازنة، على أرض مستوية ومجهزة. أما عند نصف قطر يبلغ 30 متراً، فقد تكون الحمولة المصنفة لنفس المعدة جزءاً صغيراً من ذلك.\n\n## الأرقام الأربعة التي تحدد الاختيار\n\n**وزن الحمل.** الكتلة الفعلية للحمل المراد رفعه، مضافاً إليها معدات الربط: الأحزمة والمشابك وعوارض التوزيع وأي عارضة رفع. تضيف معدات الربط عادةً عدة مئات من الكيلوغرامات ويتم إغفالها كثيراً.\n\n**نصف القطر.** المسافة الأفقية من مركز دوران الرافعة إلى مركز الحمل — عند نقطة الإنزال، وليس عند نقطة الالتقاط. وهذا عادةً هو القيد الحاسم، وهو الرقم الأكثر عرضة للتقدير الأقل من الواقع.\n\n**ارتفاع الرفع.** المسافة التي يجب أن يقطعها الخطاف، شاملةً ارتفاع الحمل نفسه ومعدات الربط والمسافة الآمنة فوق أي عائق.\n\n**ظروف الأرض.** أحمال الدعامات مركزة وكبيرة. الرافعة التي تطابق جدول الأحمال على الورق ثم تغوص إحدى دعاماتها في قناة خدمات لم تنفذ عملية الرفع.\n\n## كيفية استخدام جدول الأحمال\n\nلكل رافعة جدول أحمال يوضح أحمال العمل الآمنة لكل تركيبة من طول الذراع ونصف القطر. انزل إلى نصف القطر المطلوب، وانتقل أفقياً إلى تكوين الذراع لديك، وقارن الرقم بإجمالي الحمل شاملاً معدات الربط. إذا كنت ضمن حدود 80% تقريباً من رقم الجدول، فانظر إلى الفئة الأعلى — فالهامش يستوعب بدل الرياح، والوزن الذي لم يُبلَّغ عنه، ونصف القطر الذي تبيّن أنه أطول مما هو في المخطط.\n\n## حدود أي أداة إلكترونية\n\nأرسل لنا وزن الحمل ونصف القطر وارتفاع الرفع ويمكننا اقتراح فئات الرافعات المناسبة للدراسة. هذه نقطة بداية وليست خطة رفع: فملاءمة المعدة النهائية وتقييم تحمل التربة وخطة الرفع نفسها يجب أن يؤكدها مهندس رفع مؤهل عاين الموقع.",
    },
    categories: ["mobile-cranes","crawler-cranes"],
    updated: "2026-09-14",
  },
  {
    slug: { en: "mobile-vs-crawler-cranes", ar: "الرافعات-المتحركة-مقابل-الزاحفة" },
    title: { en: "Mobile crane or crawler crane?", ar: "رافعة متحركة أم رافعة زاحفة؟" },
    excerpt: { en: "The decision is usually about duration and ground, not about capacity.", ar: "القرار يتعلق عادةً بالمدة وظروف الأرض، وليس بالحمولة." },
    body: {
      en: "Both types reach similar capacities at the top end, so capacity is rarely what decides between them. Duration, ground and mobilisation cost are.\n\n## Mobile (all-terrain) cranes\n\nDrive to site on the public road network, set up on outriggers in under an hour, and drive away. Telescopic boom, so no assembly.\n\nChoose one when the work is measured in hours or days, when you have several lift locations, or when access is constrained. The economics are dominated by the day rate because mobilisation is comparatively cheap.\n\n## Crawler cranes\n\nArrive disassembled on multiple trailer loads, are built on site with an assist crane, and travel on tracks once erected. Lattice boom, higher capacity at long radius, and able to travel with a suspended load on prepared ground.\n\nChoose one for sustained duty — weeks or months on the same footprint — or where the duty cycle is heavy enough that a mobile crane would be working at the edge of its chart all day.\n\n## Where the real cost sits\n\nFor a crawler crane, mobilisation and demobilisation can be **20–40% of the total project cost**. Counterweights, boom sections and tracks all move as separate loads; the route may need surveying; permits and escorts are often required.\n\nThat is why a crawler crane quote starts with questions about the route, the site and the programme. A number for that mobilisation given before those answers would be a guess, and a guess on a figure that size is not a service.\n\n## Rough guide\n\n| Situation | Usually |\n|---|---|\n| A few lifts over one or two days | Mobile |\n| Multiple set-up positions across a site | Mobile |\n| Six weeks on one foundation | Crawler |\n| Heavy repetitive duty cycle | Crawler |\n| Tight urban access, short duration | Mobile |\n| Long radius at high capacity | Crawler |\n\nConfirm the choice with a lifting engineer against the actual load chart and site conditions.",
      ar: "يصل النوعان إلى حمولات متقاربة في الفئات العليا، لذا نادراً ما تكون الحمولة هي الفيصل بينهما. الفيصل هو المدة وظروف الأرض وتكلفة التعبئة والنقل.\n\n## الرافعات المتحركة (جميع التضاريس)\n\nتصل إلى الموقع عبر شبكة الطرق العامة، وتُجهَّز على الدعامات في أقل من ساعة، ثم تغادر. ذراع تلسكوبي، أي بدون أعمال تركيب.\n\nاخترها عندما يُقاس العمل بالساعات أو الأيام، أو عندما يكون لديك عدة مواقع رفع، أو عندما تكون المداخل محدودة. تهيمن الأجرة اليومية على الاقتصاديات لأن تكلفة التعبئة والنقل منخفضة نسبياً.\n\n## الرافعات الزاحفة\n\nتصل مفككة على عدة أحمال مقطورات، وتُركَّب في الموقع بمساعدة رافعة أخرى، وتتنقل على الجنازير بعد تركيبها. ذراع شبكي، وحمولة أعلى عند نصف القطر الطويل، وقدرة على التحرك بحمل معلق على أرض مجهزة.\n\nاخترها للأعمال المستمرة — أسابيع أو أشهر في الموقع نفسه — أو حيث تكون دورة العمل ثقيلة بما يجعل الرافعة المتحركة تعمل عند حدود جدول أحمالها طوال اليوم.\n\n## أين تكمن التكلفة الحقيقية\n\nبالنسبة للرافعة الزاحفة، قد تمثل التعبئة والإرجاع **20–40% من إجمالي تكلفة المشروع**. فالأثقال الموازنة وأقسام الذراع والجنازير تُنقل جميعها كأحمال منفصلة؛ وقد يحتاج المسار إلى دراسة؛ وغالباً ما تلزم التصاريح ومركبات المرافقة.\n\nولهذا السبب يبدأ عرض سعر الرافعة الزاحفة بأسئلة عن المسار والموقع والجدول الزمني. فأي رقم لتلك التعبئة يُعطى قبل هذه الإجابات سيكون تخميناً، والتخمين في مبلغ بهذا الحجم ليس خدمة.\n\n## دليل تقريبي\n\n| الحالة | الخيار المعتاد |\n|---|---|\n| عمليات رفع قليلة خلال يوم أو يومين | متحركة |\n| مواقع تجهيز متعددة عبر الموقع | متحركة |\n| ستة أسابيع على أساس واحد | زاحفة |\n| دورة عمل ثقيلة ومتكررة | زاحفة |\n| مداخل حضرية ضيقة ومدة قصيرة | متحركة |\n| نصف قطر طويل بحمولة عالية | زاحفة |\n\nأكّد الاختيار مع مهندس رفع بالرجوع إلى جدول الأحمال الفعلي وظروف الموقع.",
    },
    categories: ["mobile-cranes","crawler-cranes"],
    updated: "2026-09-14",
  },
  {
    slug: { en: "what-is-included-in-crane-rental", ar: "ما-الذي-يشمله-ايجار-الرافعة" },
    title: { en: "What is actually included in a crane rental?", ar: "ما الذي يشمله إيجار الرافعة فعلياً؟" },
    excerpt: { en: "Wet or dry, operator or bare, mobilisation or not — the answers that decide the real invoice.", ar: "شامل أو غير شامل، بمشغل أو بدونه، مع التعبئة أو بدونها — الإجابات التي تحدد قيمة الفاتورة الحقيقية." },
    body: {
      en: "Most disputes in equipment hire are not about the day rate. They are about what the day rate did not include.\n\n## Wet versus dry\n\nA **wet** rental includes fuel and usually the operator. A **dry** rental is the bare machine. The difference on a month-long crane hire can be a significant share of the invoice, and the terms are used inconsistently across the market.\n\nEach equipment page on this site lists what is and is not included, and a quote should state it again in writing. If it does not, ask.\n\n## Operator, and the crew beyond the operator\n\nCranes and heavy plant are normally supplied with a certified operator. What is often *not* included is the rest of the lifting team: rigger, banksman, signaller. For most lifts above about 20 tonnes you need at least one, and they are chargeable.\n\n## Mobilisation and demobilisation\n\nGetting the machine to site and back is a separate cost, charged in both directions, scaling with distance and machine class. Low-bed transport and escort vehicles add further. On the largest classes this is the single biggest line after the rental itself.\n\n## What is essentially never included\n\n- Site preparation, ground bearing assessment and crane mats\n- The lift plan and method statement\n- Permits, road closures and abnormal load approvals\n- Standby or waiting time outside the agreed shift\n- Damage beyond fair wear and tear\n\n## The deposit is not a charge\n\nA security deposit is refundable, is held separately from the rental, and carries no VAT because it is not revenue. It covers damage, missing accessories and fuel shortfall. After the return inspection any agreed deduction is itemised and the balance released.\n\nRental price, deposit, authorisation and final charge are four different figures. Any quotation that blurs them is worth questioning.",
      ar: "معظم النزاعات في تأجير المعدات لا تتعلق بالأجرة اليومية، بل بما لم تشمله تلك الأجرة.\n\n## شامل أم غير شامل\n\nالإيجار **الشامل** يتضمن الوقود وعادةً المشغل. أما الإيجار **غير الشامل** فهو المعدة وحدها. والفرق في إيجار رافعة لمدة شهر قد يمثل نسبة كبيرة من الفاتورة، ويُستخدم المصطلحان بشكل غير متسق في السوق.\n\nتوضح كل صفحة معدة في هذا الموقع ما هو مشمول وما هو غير مشمول، وينبغي أن يذكر عرض السعر ذلك كتابةً مرة أخرى. وإن لم يفعل، فاسأل.\n\n## المشغل، والطاقم بخلاف المشغل\n\nتُوفَّر الرافعات والمعدات الثقيلة عادةً مع مشغل معتمد. أما ما لا يُشمل غالباً فهو بقية فريق الرفع: فني الربط والمشير وعامل الإشارة. ولمعظم عمليات الرفع التي تتجاوز 20 طناً تقريباً تحتاج إلى واحد منهم على الأقل، وهم مدفوعو الأجر.\n\n## التعبئة والإرجاع\n\nنقل المعدة إلى الموقع وإعادتها تكلفة منفصلة، تُحتسب في الاتجاهين، وتتناسب مع المسافة وفئة المعدة. ويضيف النقل بالمقطورة المنخفضة ومركبات المرافقة تكاليف أخرى. وفي الفئات الأكبر يمثل هذا أكبر بند بعد الإيجار نفسه.\n\n## ما لا يُشمل عملياً أبداً\n\n- تجهيز الموقع وتقييم تحمل التربة وحصائر الرافعة\n- خطة الرفع وبيان الطريقة\n- التصاريح وإغلاق الطرق وموافقات الأحمال غير الاعتيادية\n- وقت الانتظار أو التوقف خارج الوردية المتفق عليها\n- الأضرار التي تتجاوز الاستهلاك الطبيعي\n\n## التأمين ليس رسماً\n\nمبلغ التأمين قابل للاسترداد، ويُحتجز بشكل منفصل عن الإيجار، ولا تُحتسب عليه ضريبة القيمة المضافة لأنه ليس إيراداً. وهو يغطي الأضرار والملحقات المفقودة ونقص الوقود. وبعد فحص الإرجاع تُفصَّل أي خصومات متفق عليها ويُفرج عن الرصيد.\n\nقيمة الإيجار والتأمين والحجز والمبلغ النهائي أربعة أرقام مختلفة. وأي عرض سعر يخلط بينها يستحق التساؤل.",
    },
    categories: ["mobile-cranes","boom-trucks","low-bed-trailers"],
    updated: "2026-09-14",
  },
];
