/**
 * GENERATED by scripts/prepare-images.mjs from src/content/images.json.
 * Do not edit by hand: change the manifest and run `npm run images:prepare`.
 */

import type { Localized } from "./catalog";

export interface ImageCredit {
  author: string;
  authorUrl: string | null;
  source: string;
  sourceUrl: string;
  license: string;
  licenseUrl: string;
}

export interface SiteImage {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
  alt: Localized;
  credit: ImageCredit;
}

export const IMAGES = {
  "hero/excavator-golden-hour": {
    "src": "/images/hero/excavator-golden-hour.48c314e342.jpg",
    "width": 2400,
    "height": 1350,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAJABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQIFBv/EACAQAAIBAwQDAAAAAAAAAAAAAAECEQADBAUSMoETIlH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABgRAAIDAAAAAAAAAAAAAAAAAAARITFB/9oADAMBAAIRAxEAPwC1ka9hYjEORtK+sqwafhEUBq2A4tv52uLckQtskT0KxFzkKfH5N1RNsl4f/9k=",
    "alt": {
      "en": "Tracked excavator working on an earthworks site in low evening sun",
      "ar": "حفار مجنزر يعمل في موقع أعمال ترابية تحت شمس المساء"
    },
    "credit": {
      "author": "Built Robotics",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/3xaxYYv1_PI",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  },
  "banner/riyadh-skyline": {
    "src": "/images/banner/riyadh-skyline.b18c3f1c1e.jpg",
    "width": 2000,
    "height": 1125,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAJABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQMEBv/EAB8QAAEDAwUAAAAAAAAAAAAAAAEAAgMEBREhIjJDcf/EABUBAQEAAAAAAAAAAAAAAAAAAAME/8QAGREBAAIDAAAAAAAAAAAAAAAAAQADAhEh/9oADAMBAAIRAxEAPwCgXGha0bwkyXKlljJyBqcZWdHFyPU31AUh3cobsmf/2Q==",
    "alt": {
      "en": "Riyadh skyline at sunset, with Kingdom Centre Tower and construction cranes at the King Abdullah Financial District",
      "ar": "أفق الرياض عند الغروب، ويظهر برج المملكة والرافعات في مركز الملك عبدالله المالي"
    },
    "credit": {
      "author": "B.alotaby",
      "authorUrl": "https://commons.wikimedia.org/wiki/User:B.alotaby",
      "source": "Wikimedia Commons",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Riyadh_Skyline_showing_the_King_Abdullah_Financial_District_(KAFD)_and_the_famous_Kingdom_Tower_.jpg",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0/"
    }
  },
  "banner/excavators-at-dusk": {
    "src": "/images/banner/excavators-at-dusk.89dc9c6bd2.jpg",
    "width": 2000,
    "height": 1125,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAEF/8QAHxAAAgIBBAMAAAAAAAAAAAAAAQIAAxEEBQYhEjFx/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAXEQADAQAAAAAAAAAAAAAAAAAAARFR/9oADAMBAAIRAxEAPwAo5Dti1IU0l3mOipx6+wlm76K4s1lVmSOgFGFmHJFekiw//9k=",
    "alt": {
      "en": "Excavators silhouetted against the sky at dusk",
      "ar": "حفارات تظهر ظلالها مقابل السماء عند الغروب"
    },
    "credit": {
      "author": "Matt Seymour",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/su28EW1eYT4",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  },
  "equipment/all-terrain-crane-50t": {
    "src": "/images/equipment/all-terrain-crane-50t.509597d405.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAMF/8QAIhAAAgEDBAIDAAAAAAAAAAAAAQIEAAMRBRITIiExM7Hw/8QAFAEBAAAAAAAAAAAAAAAAAAAAAf/EABcRAQADAAAAAAAAAAAAAAAAAAABESH/2gAMAwEAAhEDEQA/AHzByxsXXRNvcAMTuH40aFcM4PG4u3Hg3FH0ax11SazLcMi4WGcefWfdWOtTgnztRoqH/9k=",
    "alt": {
      "en": "Mobile crane set up on a city street between office towers",
      "ar": "رافعة متحركة مجهزة في شارع بين الأبراج المكتبية"
    },
    "credit": {
      "author": "WKH Studio",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/kjOaSTj9xo0",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  },
  "equipment/all-terrain-crane-100t": {
    "src": "/images/equipment/all-terrain-crane-100t.4e885d7cc3.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgMF/8QAIBAAAgIBAwUAAAAAAAAAAAAAAQIDEQASMVETIlJxgf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAXEQADAQAAAAAAAAAAAAAAAAAAAxNR/9oADAMBAAIRAxEAPwCMMJaVleJlA5K2Pl45YE0HolJH8dQF+uczYZGlfTJ3AC6OI1uFUVtQ2x2ZoIrw/9k=",
    "alt": {
      "en": "Yellow all-terrain crane parked in a sunny industrial yard",
      "ar": "رافعة جميع التضاريس صفراء متوقفة في ساحة صناعية مشمسة"
    },
    "credit": {
      "author": "Jindřich Krumhanzl",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/6fSfmrjqulw",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  },
  "equipment/all-terrain-crane-200t": {
    "src": "/images/equipment/all-terrain-crane-200t.36cc9f77de.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwQF/8QAIBAAAgEEAQUAAAAAAAAAAAAAAQIDAAQREiIFEyFi0f/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAXEQADAQAAAAAAAAAAAAAAAAAAAhEx/9oADAMBAAIRAxEAPwAm6lAspD9wqThdQTVaXltFsZ1ZAoHLbOSax1SPYlY1U+pP2kTiML4oVro4sw//2Q==",
    "alt": {
      "en": "Five-axle 200 tonne all-terrain crane on its outriggers",
      "ar": "رافعة جميع التضاريس بحمولة 200 طن وخمسة محاور على دعاماتها"
    },
    "credit": {
      "author": "K. Krallis (SV1XV)",
      "authorUrl": "https://commons.wikimedia.org/wiki/User:Sv1xv",
      "source": "Wikimedia Commons",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=9618644",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/"
    }
  },
  "equipment/crawler-crane-300t": {
    "src": "/images/equipment/crawler-crane-300t.c3a9b22a15.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQAE/8QAIRAAAgEDBAMBAAAAAAAAAAAAAQIDABESBAUhQTJRkaH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAGBEAAgMAAAAAAAAAAAAAAAAAAREAAgP/2gAMAwEAAhEDEQA/AKXdkVpHWF+chfqw7P0UhtwlbSxyYRkSdZWI9A0MNCiyK5kkY3sQxFj+Vs0MbQYhZ5mF/Fn4NEaWbcVxmQgJ/9k=",
    "alt": {
      "en": "Red lattice-boom crawler crane on tracks at a construction site",
      "ar": "رافعة زاحفة حمراء بذراع شبكي على جنازير في موقع بناء"
    },
    "credit": {
      "author": "Roger Starnes Sr",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/nQxOffcW-mg",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  },
  "equipment/boom-truck-15t": {
    "src": "/images/equipment/boom-truck-15t.0d49d10e13.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwX/xAAhEAACAgICAQUAAAAAAAAAAAABAgMRACEEMRIyUWFxkf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAaEQABBQEAAAAAAAAAAAAAAAABAAIEESEU/9oADAMBAAIRAxEAPwCjKEisUbAs2dD7whOWHkXaMKdqALb4wZuGswaUySq5XdN3+4XA4ovUkgHrKgiievbCJLq0p87bwL//2Q==",
    "alt": {
      "en": "Truck-mounted crane parked at a building site",
      "ar": "رافعة مركبة على شاحنة متوقفة في موقع بناء"
    },
    "credit": {
      "author": "Chris Boyd",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/O2g8HCgDN8o",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  },
  "equipment/forklift-3t-diesel": {
    "src": "/images/equipment/forklift-3t-diesel.5645c4bd2d.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwT/xAAgEAACAQMEAwAAAAAAAAAAAAABAgMAESEEEjFRBRMy/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAWEQEBAQAAAAAAAAAAAAAAAAAAARH/2gAMAwEAAhEDEQA/AIhrIkjJaOaJhxbihj8pLNtEgHrOGZvm/WalWZyBuO4dHNMhVkzGgv0tqmEf/9k=",
    "alt": {
      "en": "Diesel counterbalance forklift driving along a yard road",
      "ar": "رافعة شوكية ديزل تسير على طريق داخل ساحة"
    },
    "credit": {
      "author": "Bigfoot STNGR",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/QBcxhOcDU4U",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  },
  "equipment/forklift-16t-diesel": {
    "src": "/images/equipment/forklift-16t-diesel.2c4518666a.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgMEBv/EACEQAAIBAwMFAAAAAAAAAAAAAAECAwAREgQFIQYTMVFh/8QAFAEBAAAAAAAAAAAAAAAAAAAAAv/EABcRAQEBAQAAAAAAAAAAAAAAAAEAAhH/2gAMAwEAAhEDEQA/ALdZuSx6CbtzoshjbAqwvf5S4Oo4HjdjHI2HBKjK5t5rM4hoihvj6FFiWCBnYhORRdMuF//Z",
    "alt": {
      "en": "Large diesel forklift in a timber yard",
      "ar": "رافعة شوكية ديزل كبيرة في ساحة أخشاب"
    },
    "credit": {
      "author": "Bob Adams",
      "authorUrl": "https://www.flickr.com/people/46185203@N05",
      "source": "Wikimedia Commons",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=36406557",
      "license": "CC BY-SA 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0/"
    }
  },
  "equipment/telehandler-17m": {
    "src": "/images/equipment/telehandler-17m.3349a0aa1d.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAECBP/EACMQAAIBAwQBBQAAAAAAAAAAAAECAwAEEQUTITEGEkFRYXH/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/EABYRAQEBAAAAAAAAAAAAAAAAAAAREv/aAAwDAQACEQMRAD8AvTPJmljKXSYkA4deQf0Vj1C6ju7gyQNIwIwNx+/vHtRtoVUFR3mk8UZIjKL6R18ijSo//9k=",
    "alt": {
      "en": "Yellow telehandler with its boom raised in a timber yard",
      "ar": "رافعة تلسكوبية صفراء بذراع مرفوع في ساحة أخشاب"
    },
    "credit": {
      "author": "Lajos Szabo",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/lzW4Zv95-Ts",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  },
  "equipment/excavator-20t": {
    "src": "/images/equipment/excavator-20t.40fe0c773f.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAX/xAAeEAACAwABBQAAAAAAAAAAAAABAgADBCESMVGBkf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAGBEAAwEBAAAAAAAAAAAAAAAAAAIRExT/2gAMAwEAAhEDEQA/ABZ81KU9bsp8AHuY6rBVZlD8En1IeO5lVQoHyNu23qpAbgSe7UXKkP/Z",
    "alt": {
      "en": "Tracked excavator standing on sand in warm evening light",
      "ar": "حفار مجنزر على الرمل في ضوء المساء الدافئ"
    },
    "credit": {
      "author": "EESOFUFFZICH",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/bGMyTnSlYvE",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  },
  "equipment/excavator-36t": {
    "src": "/images/equipment/excavator-36t.779ecc9f2e.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwX/xAAhEAACAQQBBQEAAAAAAAAAAAABAgMABAUhERIiMYGRwf/EABUBAQEAAAAAAAAAAAAAAAAAAAAC/8QAFREBAQAAAAAAAAAAAAAAAAAAAAH/2gAMAwEAAhEDEQA/AEOeiuZkiDvbxk978b9GpmVyzRGaK2uHdWbT9ROh44P2pC6X9opzUQr/2Q==",
    "alt": {
      "en": "Large excavator working on top of an earth mound",
      "ar": "حفار كبير يعمل فوق كومة من التراب"
    },
    "credit": {
      "author": "Billy Freeman",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/nkxB5Ab-ONY",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  },
  "equipment/wheel-loader-3m3": {
    "src": "/images/equipment/wheel-loader-3m3.596a582bac.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgQFBv/EAB4QAAICAgMBAQAAAAAAAAAAAAECAyEABAURQTKR/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABgRAAMBAQAAAAAAAAAAAAAAAAABERIT/9oADAMBAAIRAxEAPwC0vNaK0JL8qsXh5iPYllj2kVFABjZW+szexqxoymItH6Qpo/uEsCqySAkEsW6HQF4G3KPzVh//2Q==",
    "alt": {
      "en": "Wheel loader carrying a full bucket of red earth",
      "ar": "لودر بعجل يحمل دلواً ممتلئاً بالتراب الأحمر"
    },
    "credit": {
      "author": "Zac Edmonds",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/N1LBcqLP9ec",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  },
  "equipment/backhoe-loader": {
    "src": "/images/equipment/backhoe-loader.c937ba9280.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQIEBf/EABwQAAICAwEBAAAAAAAAAAAAAAECAxEABBIFMf/EABUBAQEAAAAAAAAAAAAAAAAAAAAD/8QAGREBAAIDAAAAAAAAAAAAAAAAAQADERIh/9oADAMBAAIRAxEAPwBNTUh1BBNKopRZJF85XsetriNhErOwWxamszqMkIRnfk0SLwF3ii5SRqAoAn5ki1DARqL2f//Z",
    "alt": {
      "en": "Yellow backhoe loader parked beside a steel silo",
      "ar": "حفار لودر أصفر متوقف بجانب صومعة معدنية"
    },
    "credit": {
      "author": "Roger Starnes Sr",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/zU0htI8Y55M",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  },
  "equipment/boom-lift-26m": {
    "src": "/images/equipment/boom-lift-26m.ebdabde1a7.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQED/8QAHxAAAgEEAgMAAAAAAAAAAAAAAQIDAAQFESEiEjEy/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAVEQEBAAAAAAAAAAAAAAAAAAAAEf/aAAwDAQACEQMRAD8ASus7ZzWs8Cs4d4yqllIB2KzxWdto7JbdvJGhi+2HUkUa4Vz3RW512G6qoqqFRQq79LwKVI//2Q==",
    "alt": {
      "en": "Diesel articulating boom lift parked on a construction site",
      "ar": "رافعة أفراد مفصلية تعمل بالديزل متوقفة في موقع بناء"
    },
    "credit": {
      "author": "PvOberstein",
      "authorUrl": "https://commons.wikimedia.org/wiki/User:PvOberstein",
      "source": "Wikimedia Commons",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=69488940",
      "license": "CC0 1.0",
      "licenseUrl": "https://creativecommons.org/publicdomain/zero/1.0/"
    }
  },
  "equipment/scissor-lift-12m": {
    "src": "/images/equipment/scissor-lift-12m.2c77bbb72f.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAX/xAAfEAADAAEEAwEAAAAAAAAAAAABAgMRAAQSIRMVMZH/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABcRAAMBAAAAAAAAAAAAAAAAAAECEQD/2gAMAwEAAhEDEQA/ACe1DQ8FLl3JClGP3saVHcbiMSBt1KseglOOBqA12lQLhGweWWUE/ulTvStOLOwGM9HRsJusillgA3//2Q==",
    "alt": {
      "en": "Row of scissor lifts parked side by side",
      "ar": "صف من الرافعات المقصية متوقفة جنباً إلى جنب"
    },
    "credit": {
      "author": "FleetNow",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/NIq3Bjt5RIE",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  },
  "equipment/generator-500kva": {
    "src": "/images/equipment/generator-500kva.5f9c2e8beb.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAX/xAAgEAACAQMEAwAAAAAAAAAAAAABAgMABAUREiExE1GB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAL/xAAWEQEBAQAAAAAAAAAAAAAAAAABACH/2gAMAwEAAhEDEQA/AAWBx7Qa3Uzq+vW4jin20+PtbmOSB94Gu4Fz64qjnljtHWKGCIBh2UBIqN4oyvMan5RA2hv/2Q==",
    "alt": {
      "en": "Large canopied diesel generator set on a concrete pad",
      "ar": "مولد ديزل كبير بهيكل مغلق على قاعدة خرسانية"
    },
    "credit": {
      "author": "Gregsedits",
      "authorUrl": null,
      "source": "Wikimedia Commons",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:Caterpillar_(Olympian)_Generator_Set.jpg",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/"
    }
  },
  "equipment/air-compressor-375cfm": {
    "src": "/images/equipment/air-compressor-375cfm.12f3ae50c2.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAP/xAAiEAACAQQBBAMAAAAAAAAAAAABAgMABBExBQYSFCFBUZH/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAv/EABcRAQEBAQAAAAAAAAAAAAAAAAEAERL/2gAMAwEAAhEDEQA/AEy9Qlbh4cjsQ7VTkj9plpzsdzCnkAgklWVV9Y+N0d+PtsGUxAvjdSjRDqNVx9Cp5ICO7f/Z",
    "alt": {
      "en": "Towable diesel air compressor on a construction site",
      "ar": "ضاغط هواء ديزل قابل للسحب في موقع بناء"
    },
    "credit": {
      "author": "Norbert Schnitzler",
      "authorUrl": "https://commons.wikimedia.org/wiki/User:Timo_Beil",
      "source": "Wikimedia Commons",
      "sourceUrl": "https://commons.wikimedia.org/w/index.php?curid=2193078",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/"
    }
  },
  "equipment/dewatering-pump-6in": {
    "src": "/images/equipment/dewatering-pump-6in.ac8418625c.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwIF/8QAIBAAAgEEAQUAAAAAAAAAAAAAAQIDAAQSIREyQVGBkf/EABQBAQAAAAAAAAAAAAAAAAAAAAP/xAAWEQADAAAAAAAAAAAAAAAAAAAAARL/2gAMAwEAAhEDEQA/ALhguJooykuJYDLX0CkjtpI3Alu1bEdPBHO9eq1QA45bdHMirgCAwbz2o6Yso//Z",
    "alt": {
      "en": "Diesel trailer pumps with discharge hoses running across a site",
      "ar": "مضخات ديزل على مقطورات مع خراطيم تصريف ممتدة عبر الموقع"
    },
    "credit": {
      "author": "Marty Bahamonde / FEMA",
      "authorUrl": null,
      "source": "Wikimedia Commons",
      "sourceUrl": "https://commons.wikimedia.org/wiki/File:FEMA_-_34923_-_Pumps_being_used_to_release_pressure_on_a_levee_in_Illinois.jpg",
      "license": "Public domain",
      "licenseUrl": "https://commons.wikimedia.org/wiki/File:FEMA_-_34923_-_Pumps_being_used_to_release_pressure_on_a_levee_in_Illinois.jpg"
    }
  },
  "equipment/low-bed-trailer-60t": {
    "src": "/images/equipment/low-bed-trailer-60t.9275fb491a.jpg",
    "width": 1600,
    "height": 1200,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAMABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQID/8QAHhAAAgIDAQADAAAAAAAAAAAAAQIDEQAEIRIyQdH/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABgRAAIDAAAAAAAAAAAAAAAAAAABAgMR/9oADAMBAAIRAxEAPwBqXZ2ovlKPIFlggP5kJvvOlJOT65wBThEiCZ6ez9cNZvrwrrswjLUekE3kHNjVen//2Q==",
    "alt": {
      "en": "Low-bed trailer carrying a wheel loader across a large earthworks site",
      "ar": "مقطورة منخفضة تحمل لودراً بعجل عبر موقع أعمال ترابية كبير"
    },
    "credit": {
      "author": "Troy Mortier",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/4wj8Rs9SJeQ",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  },
  "project/jubail-plant-expansion-lifts": {
    "src": "/images/project/jubail-plant-expansion-lifts.3ee0c1afe4.jpg",
    "width": 1600,
    "height": 1000,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAKABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgMG/8QAIRAAAgEDAwUAAAAAAAAAAAAAAQIDABIhBBETMUFxgYL/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAGBEAAgMAAAAAAAAAAAAAAAAAAREAAgP/2gAMAwEAAhEDEQA/AFaUWNY8SMwPTfHeqcSam8ILWXe4NgD3WaE8qjErjwxoyamcjM0h+jSnazcAY1SM/9k=",
    "alt": {
      "en": "Process plant under construction on the coast, with crawler cranes working beside the steel structures",
      "ar": "مصنع معالجة قيد الإنشاء على الساحل، مع رافعات زاحفة تعمل بجوار الهياكل الحديدية"
    },
    "credit": {
      "author": "Julia Taubitz",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/industrial-complex-with-pipes-and-structures-by-the-water-RlY5ZtptWvM",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  },
  "project/riyadh-solar-plant-lifts": {
    "src": "/images/project/riyadh-solar-plant-lifts.66bfceb058.jpg",
    "width": 1600,
    "height": 1000,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAKABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQMEBf/EAB8QAAIBBAIDAAAAAAAAAAAAAAECAwAFERIEMSFRkv/EABUBAQEAAAAAAAAAAAAAAAAAAAED/8QAFxEBAQEBAAAAAAAAAAAAAAAAAQACIf/aAAwDAQACEQMRAD8ArW6zlNjOvwKRNdOfjaMh19qBkVlwHJAPRPVBmZVRlYht8ZB81PKvIv/Z",
    "alt": {
      "en": "Aerial view of a solar power plant, with a mobile crane setting a station between rows of panels and trucks waiting to unload",
      "ar": "منظر جوي لمحطة طاقة شمسية، ورافعة متحركة تركّب محطة بين صفوف الألواح وشاحنات تنتظر التفريغ"
    },
    "credit": {
      "author": "Vlad Burac",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/aerial-view-of-a-solar-panel-field-with-a-crane-QQRumEY3PrM",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  },
  "project/dammam-warehouse-roof-steel": {
    "src": "/images/project/dammam-warehouse-roof-steel.77f80be0d4.jpg",
    "width": 1600,
    "height": 1000,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAKABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQIEBf/EACAQAAIBBAEFAAAAAAAAAAAAAAERAAIDEiGBBRMUMdH/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/8QAFREBAQAAAAAAAAAAAAAAAAAAAQD/2gAMAwEAAhEDEQA/AIh0+pP0AdrUHikUZdq4Tx9m3ZDs1PcW4AiFrAlcxqxv/9k=",
    "alt": {
      "en": "Two workers on a scissor lift beneath the steel roof trusses of a large building",
      "ar": "عاملان على منصة مقصية أسفل جمالونات السقف الحديدية لمبنى كبير"
    },
    "credit": {
      "author": "Jimmy Nilsson Masth",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/men-on-a-construction-site-ewvx5TahIFA",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  },
  "project/riyadh-water-pipeline-trenching": {
    "src": "/images/project/riyadh-water-pipeline-trenching.a302ebebe8.jpg",
    "width": 1600,
    "height": 1000,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAKABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwUG/8QAIRAAAgAFBAMAAAAAAAAAAAAAAQIAAwUREgQTITIxQXH/xAAVAQEBAAAAAAAAAAAAAAAAAAADBP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ALIriIBkQE9sfIhp9d02nxzfuAVJjGVBjtNyekPUQGpSX5sku1/hiYr/2Q==",
    "alt": {
      "en": "Excavator working beside an open trench with two pipelines laid along it, in dusty light",
      "ar": "حفار يعمل بجوار خندق مفتوح مُدّ على امتداده خطا أنابيب، في أجواء غبار"
    },
    "credit": {
      "author": "roman pentin",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/excavator-beside-large-pipes-T5QT2bmiD4E",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  },
  "project/khobar-plant-relocation": {
    "src": "/images/project/khobar-plant-relocation.dbe0b8dcd3.jpg",
    "width": 1600,
    "height": 1000,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAKABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwAE/8QAHRABAAICAgMAAAAAAAAAAAAAAQIDACERQRIxMv/EABUBAQEAAAAAAAAAAAAAAAAAAAAB/8QAGBEAAwEBAAAAAAAAAAAAAAAAAAECQRL/2gAMAwEAAhEDEQA/AFLBkx4PI9nZkXRl8o7405mvqrZq1xVdqYddcI2x4hE30ZHVLRzLw//Z",
    "alt": {
      "en": "Prime mover hauling a large earthmoving scraper on a multi-axle low-bed trailer along a highway",
      "ar": "شاحنة جر تنقل كاشطة ترابية كبيرة على مقطورة منخفضة متعددة المحاور على طريق سريع"
    },
    "credit": {
      "author": "Preston A Larimer",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/a-semi-truck-hauling-a-tractor-trailer-down-a-road-5ffMql3mX_o",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  },
  "project/jeddah-coastal-site-preparation": {
    "src": "/images/project/jeddah-coastal-site-preparation.63d317e2eb.jpg",
    "width": 1600,
    "height": 1000,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABIMDRANCxIQDhAUExIVGywdGxgYGzYnKSAsQDlEQz85Pj1HUGZXR0thTT0+WXlaYWltcnNyRVV9hnxvhWZwcm7/2wBDARMUFBsXGzQdHTRuST5Jbm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm5ubm7/wAARCAAKABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAQQF/8QAHhAAAgICAgMAAAAAAAAAAAAAAQIDEQAhBBQxUWH/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//EABgRAAMBAQAAAAAAAAAAAAAAAAACURIT/9oADAMBAAIRAxEAPwDReONVuHjSyUa0Rv7gsQkhDdWVHJ2rrQG/eMRIZaJGWkmvOT6NR4WH/9k=",
    "alt": {
      "en": "Wheel loader and two dump trucks on a sunny coastal site beside a white building and palm trees",
      "ar": "لودر وشاحنتا قلاب في موقع ساحلي مشمس بجوار مبنى أبيض وأشجار نخيل"
    },
    "credit": {
      "author": "Sorin Basangeac",
      "authorUrl": null,
      "source": "Unsplash",
      "sourceUrl": "https://unsplash.com/photos/yellow-loader-and-trucks-at-a-construction-site-F86NXvreefg",
      "license": "Unsplash License",
      "licenseUrl": "https://unsplash.com/license"
    }
  }
} as const satisfies Record<string, SiteImage>;

export type ImageKey = keyof typeof IMAGES;
